apiVersion: core.federation.k8s.io/v1alpha1
kind: FederatedDeployment
metadata:
  name: http-tester-server
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: http-tester-server
    spec:
      replicas: 3
      selector:
        matchLabels:
          app.kubernetes.io/name: http-tester-server
      template:
        metadata:
          labels:
            app.kubernetes.io/name: http-tester-server
        spec:
          containers:
          - image: bjornsv/http-server:1.0
            name: http-tester-server
            imagePullPolicy: Always
            ports:
              - name: http
                containerPort: 50000
                protocol: TCP
