apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: http-tester-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-tester-client
  template:
    metadata:
      labels:
        app: http-tester-client
    spec:
      containers:
      - name: http-tester-client
        image: bjornsv/http-client:1.1
        imagePullPolicy: Always
        env:
          - name: HOST
            value: http-tester-server.default.global
            #value: http-tester-server
            #value: http-tester-server.default.svc.cluster.local
          - name: PORT
            value: "3000"
