apiVersion: core.federation.k8s.io/v1alpha1
kind: FederatedService
metadata:
  name: http-tester-client
spec:
  template:
    spec:
      selector:
        app.kubernetes.io/name: http-tester-client
      type: ClusterIP
      ports:
        - port: 80
          targetPort: http
          protocol: TCP
          name: http
